Class {
	#name : 'BPatternSearchRule',
	#superclass : 'OCSearchRule',
	#category : 'BPatterns',
	#package : 'BPatterns'
}

{ #category : 'accessing' }
BPatternSearchRule >> answerBlock [

	^ answerBlock
]

{ #category : 'accessing' }
BPatternSearchRule >> answerBlock: anObject [

	answerBlock := anObject
]

{ #category : 'accessing' }
BPatternSearchRule >> searchTree: anObject [

	searchTree := anObject
]
